### ISSUE TITLE
GUI Builder Version Error

### ISSUE THREAD

**Issue by HioBoy** [ninscope/Software#3]
<img width="247" alt="1702540356359" src="https://github.com/ninscope/Software/assets/6121576/edc1424e-2968-4b43-b4a5-fa0b98be4f23">

Which version should I choose?

**Comment by andresdegroot** [comment]
It's G4P 4.3.6 . 
You can download it here:
https://sourceforge.net/projects/g4p/files/G4P%20V4.3.5.zip/download.

**Comment by HioBoy** [comment]
thank you
